/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brands */
        get: operations["brands_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch */
        post: operations["create_batch_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Batch */
        get: operations["read_batch_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_items__item_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Batch */
        Batch: {
            /** Id */
            id: string;
            /** Brand Id */
            brand_id: string;
            /** Source Name */
            source_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** BatchCreated */
        BatchCreated: {
            /** Batch Id */
            batch_id: string;
        };
        /** BatchResponse */
        BatchResponse: {
            batch: components["schemas"]["Batch"];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            totals: components["schemas"]["BatchTotals"];
            /** Items */
            items: components["schemas"]["Item"][];
        };
        /** BatchTotals */
        BatchTotals: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Cached Prompt Tokens
             * @default 0
             */
            cached_prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /** Cost Usd */
            cost_usd?: string | null;
            /** Saved Usd */
            saved_usd?: string | null;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
        };
        /** Body_create_batch_batches_post */
        Body_create_batch_batches_post: {
            /** File */
            file: string;
            /** Brand Id */
            brand_id: string;
        };
        /** BrandSummary */
        BrandSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * CheckName
         * @enum {string}
         */
        CheckName: "number" | "entity" | "origin" | "claim" | "absence";
        /**
         * Finding
         * @description One unsupported or forbidden span, located for the reviewer.
         */
        Finding: {
            check: components["schemas"]["CheckName"];
            /** Field */
            field: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
        };
        /**
         * GeneratedCopy
         * @description The model's proposal. Valid shape here says nothing about factual support.
         */
        GeneratedCopy: {
            /** Title */
            title: string;
            /** Short Description */
            short_description: string;
            /** Description */
            description: string;
            /** Bullets */
            bullets: string[];
            /** Seo Title */
            seo_title: string;
            /** Meta Description */
            meta_description: string;
        };
        /**
         * GenerationParams
         * @description Sampling parameters that change the output and therefore the cache key.
         */
        GenerationParams: {
            /** Model */
            model: string;
            /** Temperature */
            temperature: number;
            /** Reasoning Effort */
            reasoning_effort?: ("low" | "medium" | "high") | null;
            /** Max Completion Tokens */
            max_completion_tokens: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Provider Reachable */
            provider_reachable: boolean;
            /** Model */
            model: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Detail */
            detail?: string | null;
        };
        /** Item */
        Item: {
            /** Id */
            id: string;
            /** Batch Id */
            batch_id: string;
            /** Row Number */
            row_number: number;
            facts: components["schemas"]["ProductFacts"];
            /** @default pending */
            status: components["schemas"]["Status"];
            output?: components["schemas"]["GeneratedCopy"] | null;
            /** Findings */
            findings?: components["schemas"]["Finding"][];
            /** Error */
            error?: string | null;
            /** Raw Output */
            raw_output?: string | null;
            provenance?: components["schemas"]["Provenance"] | null;
        };
        /**
         * ProductFacts
         * @description One catalogue row: the only source of truth a generated text may draw on.
         */
        ProductFacts: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Product Type */
            product_type?: string | null;
            /** Stones */
            stones?: string[];
            /** Colours */
            colours?: string[];
            /** Materials */
            materials?: string[];
            /** Size Mm */
            size_mm?: string | null;
            /** Weight G */
            weight_g?: string | null;
            /** Pieces */
            pieces?: number | null;
            /** Origin */
            origin?: string | null;
            /** Price Eur */
            price_eur?: string | null;
        };
        /** Provenance */
        Provenance: {
            /** Brand Id */
            brand_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Prompt Fingerprint */
            prompt_fingerprint: string;
            params: components["schemas"]["GenerationParams"];
            usage?: components["schemas"]["TokenUsage"];
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Cost Usd */
            cost_usd?: string | null;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "block" | "warn";
        /**
         * Status
         * @enum {string}
         */
        Status: "pending" | "processing" | "approved" | "needs_review" | "failed";
        /** TokenUsage */
        TokenUsage: {
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Cached Prompt Tokens
             * @default 0
             */
            cached_prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    brands_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandSummary"][];
                };
            };
        };
    };
    create_batch_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_batch_batches_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_batch_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_items__item_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
